# Generated by Django 4.1.6 on 2023-08-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('hometown', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
